{% set name = "pygeoprocessing" %}
{% set version = "2.4.11" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e1f49e4f925400f140280120b2ba563263c96f0ae11a8b12444bcc899d2787a

build:
  skip:  # Skip specific combinations of libgdal/python here
    - true  # [ libgdal == "3.9" and py >= 314 ]
  number: 0
  # adding --no-deps to rely on conda-managed numpy, not what's in requirements.txt.
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  script_env:
    - PYGEOPROCESSING_GDAL_LIB_PATH={{ CONDA_PREFIX }}/Library

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython >=3
    - numpy
    - setuptools
    - setuptools_scm
    - libgdal-core {{ libgdal }}
  run:
    - python
    - rtree >=0.8.3
    - scipy !=0.19.1,>=0.14.1
    - gdal >=3.0.4
    - libgdal-core {{ libgdal }}  # install the same version we build against
    - shapely >=1.6.4
    - setuptools
    - importlib-metadata

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - pygeoprocessing
    - pygeoprocessing.routing
    - pygeoprocessing.multiprocessing
  commands:
    # Skipping a single test that's failing.  Pygeoprocessing shouldn't be testing GDAL functionality anyways.
    # Skip on aarch64 and ppcle64 because there's an issue with the tests causing some to hang (and only on these platforms, only on Azure it seems)
    #     aarch64 and ppcle64 builds are less-used, so this is probably fine for now until we can fix this.
    #     See https://github.com/conda-forge/pygeoprocessing-feedstock/issues/50
    - pytest -vs tests -o log_cli=True -k "not test_create_raster_from_vector_extents_invalid_pixeltype"  # [ not (aarch64 or ppc64le) ]

about:
  home: https://github.com/natcap/pygeoprocessing
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Raster, vector, and hydrological operations for GIS processing
  dev_url: https://github.com/natcap/pygeoprocessing

extra:
  recipe-maintainers:
    - dcdenu4
    - phargogh
