{% set name = "pygeoprocessing" %}
{% set version = "2.4.6" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a7440cfa7998b701313ef5026195d10737e9cc52b900b00a8ef54f62b0912dd

build:
  number: 1
  # adding --no-deps to rely on conda-managed numpy, not what's in requirements.txt.
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython >=3
    - numpy
    - setuptools
    - setuptools_scm
  run:
    - python
    - rtree >=0.8.3
    - scipy !=0.19.1,>=0.14.1
    - gdal >=3.0.4
    - shapely >=1.6.4
    - setuptools
    - importlib-metadata

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - pygeoprocessing
    - pygeoprocessing.routing
    - pygeoprocessing.multiprocessing
  commands:
    # skipping for now due to change in GDAL exceptions: 
    # https://github.com/conda-forge/pygeoprocessing-feedstock/pull/35
    - |
      pytest \
      --deselect=tests/test_geoprocessing.py::test_get_raster_info_error_handling \
      --deselect=tests/test_geoprocessing.py::test_get_vector_info_error_handling \
      tests

about:
  home: https://github.com/natcap/pygeoprocessing
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Raster, vector, and hydrological operations for GIS processing
  dev_url: https://github.com/natcap/pygeoprocessing

extra:
  recipe-maintainers:
    - dcdenu4
    - phargogh
