{% set name = "pygeoprocessing" %}
{% set version = "2.3.4" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4276f760c6409683b85dd6e42693982dc5f7f56cd8a969a996c609da2c050a1b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - rtree >=0.8.3
    - scipy !=0.19.1,>=0.14.1
    - gdal >=3.0.4
    - shapely >=1.6.4
    - setuptools

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - pygeoprocessing
    - pygeoprocessing.routing
    - pygeoprocessing.multiprocessing
  commands:
    - pytest tests

about:
  home: https://github.com/natcap/pygeoprocessing
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Raster, vector, and hydrological operations for GIS processing
  dev_url: https://github.com/natcap/pygeoprocessing

extra:
  recipe-maintainers:
    - dcdenu4
    - phargogh
